import { DataSource } from 'typeorm';
import { Supplier } from '@bpm/data/models/supplier.entity';

export async function seedSuppliers(dataSource: DataSource) {
  const repo = dataSource.getRepository(Supplier);
  const existing = await repo.count();
  if (existing > 0) {
    console.log('🛑 Supplier already exist. Skipping...');
    return;
  }

  const suppliers = [
    {
      CompanyName: 'Exotic Liquids',
      ContactName: 'Charlotte Cooper',
      ContactTitle: 'Purchasing Manager',
      Address: '49 Gilbert St.',
      City: 'London',
      Region: '',
      PostalCode: 'EC1 4SD',
      Country: 'UK',
      Phone: '(171) 555-2222',
      Fax: '',
      HomePage: '',
    },
    {
      CompanyName: 'New Orleans Cajun Delights',
      ContactName: 'Shelley Burke',
      ContactTitle: 'Order Administrator',
      Address: 'P.O. Box 78934',
      City: 'New Orleans',
      Region: 'LA',
      PostalCode: '70117',
      Country: 'USA',
      Phone: '(100) 555-4822',
      Fax: '(100) 555-3782',
      HomePage: '',
    },
    {
      CompanyName: 'Grandma Kelly’s Homestead',
      ContactName: 'Regina Murphy',
      ContactTitle: 'Sales Representative',
      Address: '707 Oxford Rd.',
      City: 'Ann Arbor',
      Region: 'MI',
      PostalCode: '48104',
      Country: 'USA',
      Phone: '(313) 555-5735',
      Fax: '(313) 555-3349',
      HomePage: '',
    },
    {
      CompanyName: 'Tokyo Traders',
      ContactName: 'Yoshi Nagase',
      ContactTitle: 'Marketing Manager',
      Address: '9-8 Sekimai Musashino-shi',
      City: 'Tokyo',
      Region: '',
      PostalCode: '100-0001',
      Country: 'Japan',
      Phone: '(03) 3555-5011',
      Fax: '(03) 3555-5012',
      HomePage: '',
    },
    {
      CompanyName: 'Cooperativa de Quesos “Las Cabras”',
      ContactName: 'Antonio del Valle Saavedra',
      ContactTitle: 'Export Administrator',
      Address: 'Calle del Rosal 4',
      City: 'Oviedo',
      Region: 'Asturias',
      PostalCode: '33007',
      Country: 'Spain',
      Phone: '(98) 598 76 54',
      Fax: '',
      HomePage: '',
    },
    {
      CompanyName: 'Mayumi’s',
      ContactName: 'Mayumi Ohno',
      ContactTitle: 'Marketing Representative',
      Address: '92 Setsuko Chuo-ku',
      City: 'Osaka',
      Region: '',
      PostalCode: '545',
      Country: 'Japan',
      Phone: '(06) 431-7877',
      Fax: '(06) 431-7878',
      HomePage: '',
    },
    {
      CompanyName: 'Pavlova, Ltd.',
      ContactName: 'Ian Devling',
      ContactTitle: 'Marketing Manager',
      Address: '74 Rose St. Moonie Ponds',
      City: 'Melbourne',
      Region: 'Victoria',
      PostalCode: '3058',
      Country: 'Australia',
      Phone: '(03) 444-2343',
      Fax: '',
      HomePage: '',
    },
    {
      CompanyName: 'Specialty Biscuits, Ltd.',
      ContactName: 'Peter Wilson',
      ContactTitle: 'Sales Representative',
      Address: '29 King’s Way',
      City: 'Manchester',
      Region: '',
      PostalCode: 'M14 GSD',
      Country: 'UK',
      Phone: '(161) 555-4448',
      Fax: '',
      HomePage: '',
    },
    {
      CompanyName: 'PB Knäckebröd AB',
      ContactName: 'Lars Peterson',
      ContactTitle: 'Sales Agent',
      Address: 'Kaloadagatan 13',
      City: 'Göteborg',
      Region: '',
      PostalCode: 'S-345 67',
      Country: 'Sweden',
      Phone: '031-987 65 43',
      Fax: '031-987 65 91',
      HomePage: '',
    },
    {
      CompanyName: 'Refrescos Americanas LTDA',
      ContactName: 'Carlos Diaz',
      ContactTitle: 'Marketing Manager',
      Address: 'Av. das Americanas 12.890',
      City: 'São Paulo',
      Region: 'SP',
      PostalCode: '5442',
      Country: 'Brazil',
      Phone: '(11) 555 4640',
      Fax: '',
      HomePage: '',
    },
  ].map((s) => repo.create(s));

  await repo.save(suppliers);
  console.log('✅ Seeded Suppliers');
}
