---
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.application.name }}-srv'
  namespace: '{{ .Values.application.namespace }}'
spec:
  selector:
    app: '{{ .Values.application.name }}-app'
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
