name: Apply Access Control

on:
  push:
    branches:
      - main
    paths:
      - '.github/access-control/acl.yml'

jobs:
  apply-acl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pyyaml requests

      - name: Apply access control
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python .github/scripts/apply_acl.py
